### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '1 2'

### ISSUE THREAD

**Issue by kevinkle** [superphy/prairiedog#47]
```
(venv) kevin@phac5021225:~/diffpool$ python -m train --bmname=KMERS --assign-ratio=0.1 --hidden-dim=30 --output-dim=30 --cuda=0 --num-classes=6 --method=soft-assign --benchmark-iterations=1
Remove existing log dir:  log/KMERS_soft-assign_l3x1_ar10_h30_o30
CUDA 0

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kevin/diffpool/train.py", line 665, in <module>
    main()
  File "/home/kevin/diffpool/train.py", line 653, in main
    iterations=prog_args.benchmark_iterations)
  File "/home/kevin/diffpool/train.py", line 487, in benchmark_task_val
    graphs = load_data.read_graphfile(args.datadir, args.bmname, max_nodes=args.max_nodes)
  File "/home/kevin/diffpool/load_data.py", line 76, in read_graphfile
    e0,e1=(int(line[0].strip(" ")),int(line[1].strip(" ")))
ValueError: invalid literal for int() with base 10: '1 2'
```

**Comment by kevinkle** [comment]
We were missing commas, this is fixed
