### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by kevinkle** [superphy/prairiedog#49]
```
(venv) kevin@rockets:~/prairiedog/diffpool$ python -m train --bmname=KMERS --assign-ratio=0.1 --hidden-dim=30 --output-dim=30 --cuda=0 --num-classes=6 --method=soft-assign --benchmark-iterations=1
CUDA 0
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kevin/prairiedog/diffpool/train.py", line 665, in <module>
    main()
  File "/home/kevin/prairiedog/diffpool/train.py", line 653, in main
    iterations=prog_args.benchmark_iterations)
  File "/home/kevin/prairiedog/diffpool/train.py", line 492, in benchmark_task_val
    elif feat == 'node-label' and 'label' in graphs[0].node[0]:
IndexError: list index out of range
```

**Comment by kevinkle** [comment]
Fixed in https://github.com/superphy/diffpool/commit/ab09cb0a7fe4a243c969485bb83e9ac44ea92608
